name: php
type: php:5.6
build:
    flavor: symfony


web:
    document_root: "/web"
    passthru: "/index.php"

disk: 2048

mounts:
    "/logs": "shared:files/logs"

hooks:
    build: |
        mkdir -p logs
